openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://stream-orders-api-sandbox.herokuapp.com/client_api/v2/'
  - description: Production Endpoint
    url: 'https://orders-api-production.vatit-stream.com/client_api/v2/'
info:
  description: >
    <i> Please note that the v2 endpoint is in beta and is actively changing.
    </i>

    <p> <b> Find our version 1 docs here <a
    href="https://orders-api-v2-docs.vatit-stream.com/swagger-ui/#/">
    https://orders-api-docs.vatit-stream.com/swagger-ui/#/ </a> </b> </p>

    <b>Update 2.2 (2022-01-14) - Updated Quote and Order Endpoints ; </b>

    <ul>
      <li>Added classification to origin and destination address on quote and order
      <li>Added clearance details to order
    </ul>

    <b>Update 2.1 (2022-01-14) - Separate Waybills Endpoint</b>

    <ul>
      <li>Improved error messages from service providers.
      <li>Placing an order and generating a waybill have been separated into 2 separate endpoints.
      <li>Place an order by posting to <i>/orders</i> endpoint.
      <li>Generate waybill with a post to <i>/orders/{order_id}/waybills</i>. </i>
    </ul>

    <b>Update 2.0 (2021-12-23) - API Documentation for Stream</b>

    <ul>
      <li>Added the ability to send in full address details at the quoting stage.
    </ul>
  version: '2'
  title: Stream API
  contact:
    email: developers@vatitstream.com
tags:
  - name: Initial Authentication
    description: Used to generate the bearer token
  - name: Quote
    description: The flow for creating and fetching quotes
  - name: Order
    description: >-
      The flow for creating and fetching orders along with additional operations
      which can be performed on orders. <br> <br> <strong>A note for the
      addresses posted</strong>: Import and Export code refer to specific codes
      used for importing/exporting to different countries eg. <ul>
        <li>ZA: Import Number/Export Number</li>
        <li>USA: EIN</li>
        <li>UK: EORI</li>
      </ul>
  - name: Static Data
    description: Used for lookup of information
  - name: Webhook
    description: >-
      Used to subscribe to system events. When an event of the chosen type
      occurs Stream will make a post request with the event information to the
      target_url you have provided. The schema of the event payload can be seen
      under webhook_event
security:
  - bearerAuth: []
